### PR TITLE
Handle captures with missing ‘x’

### LINKED ISSUE #375: [Bug] Permissive Parser failing on certain type of non-standard captures
Using chess.js 1.0.0-beta.2

Noticed a small bug in the permissive parser for non-standard moves that result in a capture. Happens when the move doesn't indicate itself as a capture (no 'x'):

```
// with pieces:
const Chess = require('chess.js');

const chess = new Chess.Chess("r1bqk2r/p1p2pp1/2n1pn2/1p5p/2pP4/bPNB1PN1/PB1Q2PP/R3K2R w KQkq - 0 12");

console.log(chess.ascii());
console.log(chess.moves({square: 'b2'}));
console.log(chess.move('Ba3', { strict: false }));
```

image
```
// with pawns:
const Chess = require('chess.js');

const chess = new Chess.Chess("r1bqk2r/p1p2pp1/2n1pn2/1p5p/2pP4/bPNB1PN1/PB1Q2PP/R3K2R w KQkq - 0 12");

console.log(chess.ascii());
console.log(chess.moves({square: 'b3'}));
console.log(chess.move('bc4', { strict: false }));
```

image

Expected this to work based off the list of moves that permissive parser should interpret correctly:

image

Thanks to everyone who contributes to this library!

### PR DESCRIPTION
**Pull request by neofight78**
fixes #375

### CODE REVIEW

**Comment by jhlywa** [comment]
This is great!  Thanks for taking the time to dig into the crazy move parsing code. The post 1.0.0 release of chess.js will have a grammar-based parser, which should make things a bit more sane. Two quick questions: 

- Does your code handle pawn captures?
```js
const chess = new Chess('rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 2')
chess.move('ef4')
```

- How about en passant?
```js
const chess = new Chess('rnbqkbnr/pppp1ppp/8/8/4PpP1/8/PPPP3P/RNBQKBNR b KQkq g3 0 3')
chess.move('eg3')
```
If so, could you please add those two cases to the test suite as well?

Thanks again @neofight78!

**Comment by neofight78** [comment]
@jhlywa Good thinking! Additional test cases added.

**Comment by jhlywa** [comment]
One last interesting position:

```js
const chess = new Chess('7k/8/8/8/1pPb4/8/8/7K b - c3 0 1')

// chess.move('Bb3') // should move the bishop
// chess.move('bxb3') // should be an en passant capture

chess.move('bb3') // does that move the pawn or the bishop?
```

**Comment by neofight78** [comment]
Very cunning! Interestingly it's a case that already fails on the main branch too with 'bxb3'. So maybe one to fix on a different PR?

`test('moves - permissive parser (pawn bishop ambiguity)', () => {
  const fen = '7k/8/8/8/1pPb4/8/8/7K b - c3 0 1'
  const next = '7k/8/8/8/3b4/2p5/8/7K w - - 0 2'
  const chess = new Chess(fen)
  expect(chess.move('bxb3')).toMatchObject({
    to: 'c3',
    from: 'b4',
    piece: 'p',
  })
  expect(chess.fen()).toBe(next)
})
`

**Comment by neofight78** [comment]
Oh hang on you mean bc3, not bb3! 😅 Yes, in which case the main branch is fine and I need to add a fix here...

**Comment by jhlywa** [comment]
Perfect!  Thanks for you contribution @neofight78!

**Pull request merged**
