### PR TITLE
Loading PGN data containing SetUp and FEN tags causes header information to be lost

### PR DESCRIPTION
**Pull request by siansell**
With reference to #129.

I have added a couple of tests, but am new to writing JS tests (and GitHub/PRs in general), so please critically review.

### CODE REVIEW

**Comment by jhlywa** [comment]
Looks good.  Thanks for the PR

**Comment by captainsano** [comment]
This bug seems to be occurring in version 0.10.2 for the following pgn headers:

```
[Event "10th Tal Mem 2016"]
[Site "Moscow RUS"]
[Date "2016.10.06"]
[Round "9"]
[White "Li, Chao"]
[Black "Giri, Anish"]
[Result "1/2-1/2"]
[WhiteElo "2746"]
[BlackElo "2755"]
[ECO "E21"]
[EventDate "2016.10.06"]
[CurrentPosition "8/5N2/R7/4p3/4Pk1p/P3nP2/2r5/6K1 b - - 0 43"]
[SetUp "1"]
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"]
```

**Comment by siansell** [comment]
Yeah, the version pulled down from NPM (0.10.2) hasn't been updated and doesn't include this PR.

**Comment by glandre** [comment]
Any ETA for deploying the version containing this Fix to NPM?

**Pull request merged**
