### PR TITLE
added move_to_gan() function which converts a move into Grid Algebraic Notation

### PR DESCRIPTION
**Pull request by RuthShryock**
useful for generating moves with chess engines

### CODE REVIEW

**Comment by RuthShryock** [comment]
resolves #259

**Comment by ajax333221** [comment]
> resolves #259

UCI move castling is like for example: **e1g1**, but the `move_to_gan()` seems to use: **O-O**

**Comment by ajax333221** [comment]
now that it is basically move_to_uci() shouldn't it be named like that? (just a thought, I don't know hehe)

(-:

**Comment by RuthShryock** [comment]
yes thanks :)

**Comment by eiannimaersk** [comment]
You should add the new method into the documentation as well so it's easy to find for new users.

**Comment by jhlywa** [comment]
This was recently added to master under the `lan` (Long Algebraic Notation) field.

**Pull request closed without merging**
